jobs:
  include:
    - stage : Backend
      language: python
      python: "2.7"
      before_install:
          - cat .travis.yml
          - pip install --upgrade pip
          - pip --version
      install:
          - pip install -r backend/requirements.txt
          - pip install -r requirements.txt

      script:
          - echo Running Backend Tests
          - python backend/tests.py
    - stage: Frontend
      language: node_js
      node_js: "8.9"
      script:
        - echo Running Frontend Tests
        - npm install --prefix frontend
        - npm run test --prefix frontend &
    - stage: Postman
      language: node_js
      node_js: "8.9"
      script:
        - echo Running Postman Tests
        - npm install newman
        - node_modules/.bin/newman run Postman.json