jobs:
  include:
    - stage: Frontend
      language: node_js
        - "node"
      script:
        - echo Running Frontend Tests
        - npm run test --prefix idb &

    - stage : Backend
      language: python

      python:
         - "2.7"

      before_install:
          - cat .travis.yml
          - pip install --upgrade pip
          - pip --version

      install:
          - pip install -r app/requirements.txt
          - pip install -r requirements.txt

      script:
          - echo Running Backend Tests
          - python app/main.py &
          - python router.py &
          - python app/tests.py

